/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica11Imagenes2D;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.media.Buffer;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.util.BufferToImage;

/**
 *
 * @author rafa
 */
public class ventanaInternaJMFPlayer extends javax.swing.JInternalFrame {

    private Player player = null;
    private static ventana parent;

    private ventanaInternaJMFPlayer(ventana v, File f) {
        initComponents();
        //Asignamos la ventana grande original padre
        parent = v;
        String sfichero = "file:" + f.getAbsolutePath();
        MediaLocator ml = new MediaLocator(sfichero);
        try {
            player = Manager.createRealizedPlayer(ml);
            Component vc = player.getVisualComponent();
            if (vc != null) {
                add(vc, java.awt.BorderLayout.CENTER);
            }
            Component cpc = player.getControlPanelComponent();
            if (cpc != null) {
                add(cpc, java.awt.BorderLayout.SOUTH);
            }
            this.pack();
        } catch (Exception e) {
            System.err.println("ventanaInternaJMFPlayer error: " + e);
            player = null;
        }
    }

    //Funcion que llama internamente al constructor privado de la clase
    public static ventanaInternaJMFPlayer getInstance(ventana vent, File f) {
        ventanaInternaJMFPlayer v = new ventanaInternaJMFPlayer(vent, f);
        if (v.player != null) {
            return v;
        } else {
            return null;
        }
    }

    public void play() {
        if (player != null) {
            try {
                player.start();
            } catch (Exception e) {
                System.err.println("VentanaInternaJMFPlayer: " + e);
            }
        }
    }

    public void close() {
        if (player != null) {
            try {
                player.close();
            } catch (Exception e) {
                System.err.println("VentanaInternaJMFPlayer: " + e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        //Llama al metodo interno close que detiene y cierra la reproduccion
        this.close();
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("empty-statement")
  public BufferedImage captura() {
      
    FrameGrabbingControl fgc;
    String claseCtr = "javax.media.control.FrameGrabbingControl";
    fgc = (FrameGrabbingControl)this.player.getControl(claseCtr );
    
    Image img = null;
    try{
    Buffer bufferFrame = fgc.grabFrame();
    //Convertimos buffer a imagen
    BufferToImage bti;
    bti=new BufferToImage((VideoFormat)bufferFrame.getFormat());
    img = bti.createImage(bufferFrame);
    } catch (Exception e){
        System.out.println("Error al guardar la captura : " + e );
    }
    
    return (BufferedImage)img;
    
  }
}
