/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica11Imagenes2D;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.media.CannotRealizeException;
import javax.media.CaptureDeviceInfo;
import javax.media.CaptureDeviceManager;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.media.format.YUVFormat;

/**
 *
 * @author rafa
 */
public class ventanaInternaCamara extends javax.swing.JInternalFrame {

    /**
     * Creates new form ventanaInternaCamara
     */
    private Player player = null;
    private static ventana parent;

    public ventanaInternaCamara(ventana v, File f) {
        initComponents();
        //Asignamos la ventana grande original padre
        parent = v;

        try {
            CaptureDeviceInfo deviceInfo;
            List<CaptureDeviceInfo> deviceList = CaptureDeviceManager.getDeviceList(new YUVFormat());
            
                deviceInfo = deviceList.get(0);

            String sfichero = "file:" + f.getAbsolutePath();
            MediaLocator ml = deviceInfo.getLocator();
            player = Manager.createRealizedPlayer(ml);
            Component vc = player.getVisualComponent();
            if (vc != null) {
                add(vc, java.awt.BorderLayout.CENTER);
            }
            Component cpc = player.getControlPanelComponent();
            if (cpc != null) {
                add(cpc, java.awt.BorderLayout.SOUTH);
            }
            this.pack();
        } catch (Exception e) {
            System.err.println("ventanaInternaJMFPlayer: " + e);
            player = null;
        }
    }

    public static ventanaInternaCamara getInstance(ventana vent, File f) {
        ventanaInternaCamara v = new ventanaInternaCamara(vent, f);
        if (v.player != null) {
            return v;
        } else {
            return null;
        }
    }

    public void play() {
        if (player != null) {
            try {
                player.start();
            } catch (Exception e) {
                System.err.println("VentanaInternaJMFPlayer: " + e);
            }
        }

    }

    public void close() {
        if (player != null) {
            try {
                player.close();
            } catch (Exception e) {
                System.err.println("VentanaInternaJMFPlayer: " + e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        //Llama al metodo interno close que detiene y cierra la reproduccion
        this.close();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        this.play();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
