/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica11Imagenes2D;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rafa
 */
public class ventanaTamaño extends javax.swing.JInternalFrame {

     private ventana parent;
     private int widht, height;
     
    public ventanaTamaño(ventana parent) {
        initComponents();
        this.parent = parent;
        if (this.parent.getImage()!=null){
        this.widht = this.parent.getImage().getWidth();
        this.height = this.parent.getImage().getHeight();
        this.seleccionAlto.setValue(this.height);
        this.seleccionAncho.setValue(this.widht);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTamañoImagen = new javax.swing.JPanel();
        seleccionAlto = new javax.swing.JSpinner();
        seleccionAncho = new javax.swing.JSpinner();
        Alto = new javax.swing.JLabel();
        Ancho = new javax.swing.JLabel();
        reescalar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(320, 320));
        setPreferredSize(new java.awt.Dimension(250, 200));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelTamañoImagen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelTamañoImagenKeyPressed(evt);
            }
        });

        seleccionAlto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        seleccionAlto.setValue(10);
        seleccionAlto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                seleccionAltoStateChanged(evt);
            }
        });

        seleccionAncho.setValue(10);
        seleccionAncho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                seleccionAnchoStateChanged(evt);
            }
        });

        Alto.setText("Alto");

        Ancho.setText("Ancho");

        reescalar.setText("Reescalar");
        reescalar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reescalarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTamañoImagenLayout = new javax.swing.GroupLayout(panelTamañoImagen);
        panelTamañoImagen.setLayout(panelTamañoImagenLayout);
        panelTamañoImagenLayout.setHorizontalGroup(
            panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTamañoImagenLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTamañoImagenLayout.createSequentialGroup()
                        .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTamañoImagenLayout.createSequentialGroup()
                                .addComponent(Alto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seleccionAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTamañoImagenLayout.createSequentialGroup()
                                .addComponent(Ancho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seleccionAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTamañoImagenLayout.createSequentialGroup()
                        .addComponent(reescalar)
                        .addGap(34, 34, 34))))
        );
        panelTamañoImagenLayout.setVerticalGroup(
            panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTamañoImagenLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ancho))
                .addGap(18, 18, 18)
                .addComponent(reescalar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelTamañoImagen, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionAltoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_seleccionAltoStateChanged
       this.height = (int) this.seleccionAlto.getValue();
    }//GEN-LAST:event_seleccionAltoStateChanged

    private void reescalarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reescalarMouseClicked
        
        this.parent.reescalarImagen(this.widht, this.height);
         try {
             this.setClosed(true);
         } catch (PropertyVetoException ex) {
             Logger.getLogger(ventanaTamaño.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_reescalarMouseClicked

    private void seleccionAnchoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_seleccionAnchoStateChanged
        this.widht = (int) this.seleccionAncho.getValue();
    }//GEN-LAST:event_seleccionAnchoStateChanged

    private void panelTamañoImagenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelTamañoImagenKeyPressed
       this.parent.reescalarImagen(this.widht, this.height);
         try {
             this.setClosed(true);
         } catch (PropertyVetoException ex) {
             Logger.getLogger(ventanaTamaño.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_panelTamañoImagenKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        this.panelTamañoImagenKeyPressed(evt);
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alto;
    private javax.swing.JLabel Ancho;
    private javax.swing.JPanel panelTamañoImagen;
    private javax.swing.JButton reescalar;
    private javax.swing.JSpinner seleccionAlto;
    private javax.swing.JSpinner seleccionAncho;
    // End of variables declaration//GEN-END:variables
}
